$ANSIBLE_VAULT;1.1;AES256
37323737613661386139653536386638663830306137653433663263386565303261646436623562
6630613036343964623766336233623535633030336463650a313030336432376634353464623034
64303639616365643463613361356162386466336466376134666166646232343564653838373439
3938643436646133640a346339613863346432343265346463643939326130303936653738363333
64393438323637633837323831333165663565623263633734343565636635393236613261376261
31343330633866666262333733386636343133336363666531373863666662613732323335653864
35663631376165313836613731663237663239613532326632303937316438633566613662383736
31373237636633623665623530333337663037306630376236376436346531613433376161346430
37303635376136363061333061313330303364626632316165363462663363346530636331316666
30336238303164326664613164303034373561636638353663643230363966323839373863343666
323365343235346664616534353135376333
