$ANSIBLE_VAULT;1.1;AES256
37663266336132393131616661396135313933653064646562366362303530636561333563353533
3538656638343564363465636261613461613865343363650a613766343332323132346565323162
33633762313664626439323036636633663465356564666233666239393963343364343764653539
6531663536313066320a636335376230643866366135653830333332643231316664323565383765
36366264393862626330626433643934626161383661663435653036633637633764633134343465
65643866663964386333383938336538363239663133376362353030646566363566363665313562
35656264613162366365363231386566353363353938663330643464323039356661386337313939
34333064343337346631636663333836323238666531623634363237316565633833646538396362
32366230376565373664666330653038363531366230386431666334373336326462393234336135
30383436366239396439386365343037393430623763363962323336323131373639613538343664
66323233363264653234613464623232336462653163333132623937313137353666343566666437
63333365383762383933643538343064633632333565646132353564663238346437656165646661
31373363636637383433616433376630313837326462326131646665623237386361623430323233
30626138643461376638323062376637383138333437376435623964313434633538316632353366
65633132623338396231343438383938336439653539363138306437663262353138303735366530
61316335333963656238
