$ANSIBLE_VAULT;1.1;AES256
38336239396437633539376638373666643962376633623931616432666137333238366462356137
6161613665336235326638323566633534616163336131380a666434316334396332333739663361
61376431633866303336323232626234313030653434333130613163383263663037633730643030
6233336134303836310a376438393931646365613236386434636439363639323164616130623231
38376165386634376536643664356536313133613830383030663164333732323239343439353236
64306637343833653663376163643561303261393731393236393938383565393463303133353838
32656637653065313461636163663533383839343162366137343333323836323637653333316537
30393037613637623965646165633232663033333366343136616364396638336261316233313961
63626538363461653566316164383638383662363963613231306265643030313831316630336239
64363532656237633839626565656635366163306237643034303536393835393536633663396362
64326332353437396261386233323963363730366366396639336565323332323462386639306632
33363162356165666265326433623038316533363337616561316637643664333035646565626634
36383031396239313135636236306262393733383665376365356633333331363733663236623336
34306563646565646631376666646538393866306561343132383563326664626231366464323765
63633563643533393730643336633634666465666230326336303166336533343939393634336131
30383936396236613132
