---
- hosts: server
  roles:
    - application-user
    - sles-sdk
    - vmware-tools
  tags:
    - os
  remote_user: root

- hosts: server
  roles:
    - sql-server
    - nginx-config-basic
    - slack
  remote_user: "{{ ansible_user }}"
